/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-07-28 08:05:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1657720758765L));
    _jspx_dependants.put("jar:file:/C:/Users/wogml/Documents/OpenBanking/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OpenBanking/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html dir=\"ltr\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\"\r\n");
      out.write("        content=\"wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Ample lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Ample admin lite dashboard bootstrap 5 dashboard template\">\r\n");
      out.write("    <meta name=\"description\"\r\n");
      out.write("        content=\"Ample Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex,nofollow\">\r\n");
      out.write("    <title>J investment bank</title>\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://www.wrappixel.com/templates/ample-admin-lite/\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/OpenBanking/resources/images/favicon.png\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"/OpenBanking/resources/css/chartist.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/OpenBanking/resources/css/chartist-plugin-tooltip.css\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"/OpenBanking/resources/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/OpenBanking/resources/css/onlyForMe.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- FONT -->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@1&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/topAndSide.jsp", out, false);
      out.write("\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"page-wrapper\">\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"page-breadcrumb bg-white\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-sm-4 col-xs-12 mt-5\">\r\n");
      out.write("                        <h4 class=\"page-title\">ASSET STATUS</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-9 col-sm-8 col-md-8 col-xs-12\">\r\n");
      out.write("                        <div class=\"d-md-flex\">\r\n");
      out.write("                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.col-lg-12 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Three charts -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-12\">\r\n");
      out.write("                        <div class=\"white-box analytics-info\">\r\n");
      out.write("                        	 <img src=\"/OpenBanking/resources/images/bank.png\" width=\"50\" alt=\"homepage\" />\r\n");
      out.write("                            <h3 class=\"box-title\">MY ACCOUNT</h3>\r\n");
      out.write("                            <ul class=\"list-inline two-part mb-0\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                   ");
      out.write("                           </li>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-12\">\r\n");
      out.write("                        <div class=\"white-box analytics-info\">\r\n");
      out.write("                         <img src=\"/OpenBanking/resources/images/bank.png\" width=\"50\" alt=\"homepage\" />\r\n");
      out.write("                            <h3 class=\"box-title\">transfer limit</h3>\r\n");
      out.write("                            <ul class=\"list-inline two-part mb-0\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    ");
      out.write("\r\n");
      out.write("                                </li>\r\n");
      out.write("                                  ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                           		 \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-12\">\r\n");
      out.write("                        <div class=\"white-box analytics-info\">\r\n");
      out.write("                          <img src=\"/OpenBanking/resources/images/bank.png\" width=\"50\" alt=\"homepage\" />\r\n");
      out.write("                            <h3 class=\"box-title\">total balance on open banking</h3>\r\n");
      out.write("                            <ul class=\"list-inline two-part d-flex align-items-center mb-0\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div id=\"sparklinedash3\"><canvas width=\"67\" height=\"30\"\r\n");
      out.write("                                            style=\"display: inline-block; width: 67px; height: 30px; vertical-align: top;\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                \r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \r\n");
      out.write("                                \r\n");
      out.write("                                <li class=\"ms-auto\"><span class=\"counter text-info\">");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(" WON</span>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- PRODUCTS YEARLY SALES -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 col-lg-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"white-box\">\r\n");
      out.write("                       \r\n");
      out.write("                            <h1 class=\"box-title\">way to come</h1>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"d-md-flex\">\r\n");
      out.write("                                <ul class=\"list-inline d-flex ms-auto\">\r\n");
      out.write("                                    <li class=\"ps-3\">\r\n");
      out.write("                                        <h5><i class=\"fa fa-circle me-1 text-info\"></i>J INVESTMENT BANK<h5>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div id=\"map\" style=\"width000px;height:400px;\"></div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	  <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=2a5469364f4e047b9ce872e670e9dadb&libraries=services,clusterer\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("      var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("          mapOption = { \r\n");
      out.write("              center: new kakao.maps.LatLng(37.477366, 126.862592), // 지도의 중심좌표\r\n");
      out.write("              level: 3 // 지도의 확대 레벨\r\n");
      out.write("          };\r\n");
      out.write("      \r\n");
      out.write("      var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("      \r\n");
      out.write("      // 마커가 표시될 위치입니다 \r\n");
      out.write("      var markerPosition  = new kakao.maps.LatLng(37.477366, 126.862592); \r\n");
      out.write("      \r\n");
      out.write("      // 마커를 생성합니다\r\n");
      out.write("      var marker = new kakao.maps.Marker({\r\n");
      out.write("          position: markerPosition\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      // 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("      marker.setMap(map);\r\n");
      out.write("      \r\n");
      out.write("      // 아래 코드는 지도 위의 마커를 제거하는 코드입니다\r\n");
      out.write("      // marker.setMap(null);    \r\n");
      out.write("      </script>\r\n");
      out.write("	\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                           <!--  <div id=\"ct-visits\" style=\"height: 405px;\">\r\n");
      out.write("                                <div class=\"chartist-tooltip\" style=\"top: -17px; left: -12px;\"><span\r\n");
      out.write("                                        class=\"chartist-tooltip-value\">6</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>  -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- RECENT SALES -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 col-lg-12 col-sm-12\">\r\n");
      out.write("                        <div class=\"white-box\">\r\n");
      out.write("                         <h3 class=\"box-title mb-0\">RECENT WITHDRAWAL TRANSACTION</h3> \r\n");
      out.write("                            <div class=\"d-md-flex mb-3\">\r\n");
      out.write("                       \r\n");
      out.write("                             \r\n");
      out.write("	<div class=\"d-flex justify-content-center mt-5\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("				<div class=\"col\"></div>\r\n");
      out.write("					<div class=\"\">\r\n");
      out.write("				<table  class=\"table\" style=\"width:100%;\">\r\n");
      out.write("			  	<thead>\r\n");
      out.write("					<tr class=\"table-light\">\r\n");
      out.write("						<th width=\"3%\" class=\"\">#</th>\r\n");
      out.write("						<th width=\"10%\" class=\"\">DATE</th>\r\n");
      out.write("						<th width=\"30%\" class=\"\">WITHRAWAL BANK</th>\r\n");
      out.write("						<th width=\"16%\" class=\"\">DEPOSIT BANK</th>\r\n");
      out.write("						<th width=\"30%\" class=\"\">WITHRAWAL ACCOUNT</th>\r\n");
      out.write("						<th width=\"50%\" class=\"\">DEPOSIT ACCOUNT</th>\r\n");
      out.write("						<th width=\"10%\" class=\"\">SENDER </th>\r\n");
      out.write("						<th width=\"10%\" class=\"\">DEPOSITOR</th>\r\n");
      out.write("						<th width=\"10%\" class=\"\">AMOUNT</th>\r\n");
      out.write("						\r\n");
      out.write("					</tr>\r\n");
      out.write("			  </thead>	\r\n");
      out.write("		<tbody class=\"table-group-divider\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("       </div>\r\n");
      out.write("           <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 col-lg-12 col-sm-12\">\r\n");
      out.write("                        <div class=\"white-box\">\r\n");
      out.write("                         <h3 class=\"box-title mb-0\">RECENT DEPOSIT TRANSACTION</h3> \r\n");
      out.write("                            <div class=\"d-md-flex mb-3\">\r\n");
      out.write("                       \r\n");
      out.write("                             \r\n");
      out.write("	<div class=\"d-flex justify-content-center mt-5\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("				<div class=\"col\"></div>\r\n");
      out.write("					<div class=\"\">\r\n");
      out.write("				<table  class=\"table\" style=\"width:100%;\">\r\n");
      out.write("			  	<thead>\r\n");
      out.write("					<tr class=\"table-light\">\r\n");
      out.write("						<th width=\"3%\" class=\"\">#</th>\r\n");
      out.write("						<th width=\"10%\" class=\"\">DATE</th>\r\n");
      out.write("						<th width=\"30%\" class=\"\">WITHRAWAL BANK</th>\r\n");
      out.write("						<th width=\"16%\" class=\"\">DEPOSIT BANK</th>\r\n");
      out.write("						<th width=\"30%\" class=\"\">WITHRAWAL ACCOUNT</th>\r\n");
      out.write("						<th width=\"50%\" class=\"\">DEPOSIT ACCOUNT</th>\r\n");
      out.write("						<th width=\"10%\" class=\"\">SENDER </th>\r\n");
      out.write("						<th width=\"10%\" class=\"\">DEPOSITOR</th>\r\n");
      out.write("						<th width=\"10%\" class=\"\">AMOUNT</th>\r\n");
      out.write("						\r\n");
      out.write("					</tr>\r\n");
      out.write("			  </thead>	\r\n");
      out.write("		<tbody class=\"table-group-divider\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("       </div>\r\n");
      out.write("                          	\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Recent Comments -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- .col -->\r\n");
      out.write("                    <div class=\"col-md-12 col-lg-8 col-sm-12\">\r\n");
      out.write("                        <div class=\"card white-box p-0\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h3 class=\"box-title mb-0\">Recent Comments</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"comment-widgets\">\r\n");
      out.write("                                <!-- Comment Row -->\r\n");
      out.write("                                <div class=\"d-flex flex-row comment-row p-3 mt-0\">\r\n");
      out.write("                                    <div class=\"p-2\"><img src=\"/OpenBanking/resources/images/users/varun.jpg\" alt=\"user\" width=\"50\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                    <div class=\"comment-text ps-2 ps-md-3 w-100\">\r\n");
      out.write("                                        <h5 class=\"font-medium\">James Anderson</h5>\r\n");
      out.write("                                        <span class=\"mb-3 d-block\">Lorem Ipsum is simply dummy text of the printing and type setting industry.It has survived not only five centuries. </span>\r\n");
      out.write("                                        <div class=\"comment-footer d-md-flex align-items-center\">\r\n");
      out.write("                                             <span class=\"badge bg-primary rounded\">Pending</span>\r\n");
      out.write("                                             \r\n");
      out.write("                                            <div class=\"text-muted fs-2 ms-auto mt-2 mt-md-0\">April 14, 2021</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Comment Row -->\r\n");
      out.write("                                <div class=\"d-flex flex-row comment-row p-3\">\r\n");
      out.write("                                    <div class=\"p-2\"><img src=\"/OpenBanking/resources/images/users/genu.jpg\" alt=\"user\" width=\"50\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                    <div class=\"comment-text ps-2 ps-md-3 active w-100\">\r\n");
      out.write("                                        <h5 class=\"font-medium\">Michael Jorden</h5>\r\n");
      out.write("                                        <span class=\"mb-3 d-block\">Lorem Ipsum is simply dummy text of the printing and type setting industry.It has survived not only five centuries. </span>\r\n");
      out.write("                                        <div class=\"comment-footer d-md-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                                            <span class=\"badge bg-success rounded\">Approved</span>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"text-muted fs-2 ms-auto mt-2 mt-md-0\">April 14, 2021</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Comment Row -->\r\n");
      out.write("                                <div class=\"d-flex flex-row comment-row p-3\">\r\n");
      out.write("                                    <div class=\"p-2\"><img src=\"/OpenBanking/resources/images/users/ritesh.jpg\" alt=\"user\" width=\"50\" class=\"rounded-circle\"></div>\r\n");
      out.write("                                    <div class=\"comment-text ps-2 ps-md-3 w-100\">\r\n");
      out.write("                                        <h5 class=\"font-medium\">Johnathan Doeting</h5>\r\n");
      out.write("                                        <span class=\"mb-3 d-block\">Lorem Ipsum is simply dummy text of the printing and type setting industry.It has survived not only five centuries. </span>\r\n");
      out.write("                                        <div class=\"comment-footer d-md-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                                            <span class=\"badge rounded bg-danger\">Rejected</span>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"text-muted fs-2 ms-auto mt-2 mt-md-0\">April 14, 2021</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-12 col-sm-12\">\r\n");
      out.write("                        <div class=\"card white-box p-0\">\r\n");
      out.write("                            <div class=\"card-heading\">\r\n");
      out.write("                                <h3 class=\"box-title mb-0\">People I've dealt with recently</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <ul class=\"chatonline\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"call-chat\">\r\n");
      out.write("                                            <button class=\"btn btn-success text-white btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button class=\"btn btn-info btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"far fa-comments text-white\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <a href=\"javascript:void(0)\" class=\"d-flex align-items-center\"><img\r\n");
      out.write("                                                src=\"/OpenBanking/resources/images/users/varun.jpg\" alt=\"user-img\" class=\"img-circle\">\r\n");
      out.write("                                            <div class=\"ms-2\">\r\n");
      out.write("                                                <span class=\"text-dark\">Varun Dhavan <small\r\n");
      out.write("                                                        class=\"d-block text-success d-block\">online</small></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"call-chat\">\r\n");
      out.write("                                            <button class=\"btn btn-success text-white btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button class=\"btn btn-info btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"far fa-comments text-white\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <a href=\"javascript:void(0)\" class=\"d-flex align-items-center\"><img\r\n");
      out.write("                                                src=\"/OpenBanking/resources/images/users/genu.jpg\" alt=\"user-img\" class=\"img-circle\">\r\n");
      out.write("                                            <div class=\"ms-2\">\r\n");
      out.write("                                                <span class=\"text-dark\">Genelia\r\n");
      out.write("                                                    Deshmukh <small class=\"d-block text-warning\">Away</small></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"call-chat\">\r\n");
      out.write("                                            <button class=\"btn btn-success text-white btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button class=\"btn btn-info btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"far fa-comments text-white\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <a href=\"javascript:void(0)\" class=\"d-flex align-items-center\"><img\r\n");
      out.write("                                                src=\"/OpenBanking/resources/images/users/ritesh.jpg\" alt=\"user-img\" class=\"img-circle\">\r\n");
      out.write("                                            <div class=\"ms-2\">\r\n");
      out.write("                                                <span class=\"text-dark\">Ritesh\r\n");
      out.write("                                                    Deshmukh <small class=\"d-block text-danger\">Busy</small></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"call-chat\">\r\n");
      out.write("                                            <button class=\"btn btn-success text-white btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button class=\"btn btn-info btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"far fa-comments text-white\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <a href=\"javascript:void(0)\" class=\"d-flex align-items-center\"><img\r\n");
      out.write("                                                src=\"/OpenBanking/resources/images/users/arijit.jpg\" alt=\"user-img\" class=\"img-circle\">\r\n");
      out.write("                                            <div class=\"ms-2\">\r\n");
      out.write("                                                <span class=\"text-dark\">Arijit\r\n");
      out.write("                                                    Sinh <small class=\"d-block text-muted\">Offline</small></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"call-chat\">\r\n");
      out.write("                                            <button class=\"btn btn-success text-white btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button class=\"btn btn-info btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"far fa-comments text-white\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <a href=\"javascript:void(0)\" class=\"d-flex align-items-center\"><img\r\n");
      out.write("                                                src=\"/OpenBanking/resources/images/users/govinda.jpg\" alt=\"user-img\"\r\n");
      out.write("                                                class=\"img-circle\">\r\n");
      out.write("                                            <div class=\"ms-2\">\r\n");
      out.write("                                                <span class=\"text-dark\">Govinda\r\n");
      out.write("                                                    Star <small class=\"d-block text-success\">online</small></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"call-chat\">\r\n");
      out.write("                                            <button class=\"btn btn-success text-white btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button class=\"btn btn-info btn-circle btn\" type=\"button\">\r\n");
      out.write("                                                <i class=\"far fa-comments text-white\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <a href=\"javascript:void(0)\" class=\"d-flex align-items-center\"><img\r\n");
      out.write("                                                src=\"/OpenBanking/resources/images/users/hritik.jpg\" alt=\"user-img\" class=\"img-circle\">\r\n");
      out.write("                                            <div class=\"ms-2\">\r\n");
      out.write("                                                <span class=\"text-dark\">John\r\n");
      out.write("                                                    Abraham<small class=\"d-block text-success\">online</small></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.col -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("           ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Wrapper -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- All Jquery -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap tether Core JavaScript -->\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/app-style-switcher.js\"></script>\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("    <!--Wave Effects -->\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/waves.js\"></script>\r\n");
      out.write("    <!--Menu sidebar -->\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/sidebarmenu.js\"></script>\r\n");
      out.write("    <!--Custom JavaScript -->\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/custom.js\"></script>\r\n");
      out.write("    <!--This page JavaScript -->\r\n");
      out.write("    <!--chartis chart-->\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/chartist.min.js\"></script>\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("    <script src=\"/OpenBanking/resources/js/dashboard1.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /jsp/board/dashboard.jsp(92,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/board/dashboard.jsp(92,32) '${ bankList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ bankList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /jsp/board/dashboard.jsp(92,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("bankList");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("                                	                     	\r\n");
            out.write("                                	<div>\r\n");
            out.write(" 									<li class=\"ms-auto\"><span class=\"counter text-success\"><li class=\"ms-auto\"><span class=\"counter text-success\"><h5 class=\"fw-bold text-dark\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bankList.bankName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bankList.bankAlias}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('	');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bankList.accountNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" \r\n");
            out.write(" 									<p>\r\n");
            out.write(" 									balance: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bankList.balance }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" WON\r\n");
            out.write(" 									</p>\r\n");
            out.write(" 									</h5></li>   \r\n");
            out.write(" 									                           \r\n");
            out.write("                                	</span>\r\n");
            out.write("                                	</div>                                	\r\n");
            out.write("                           		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /jsp/board/dashboard.jsp(117,34) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/board/dashboard.jsp(117,34) '${ bankList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ bankList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /jsp/board/dashboard.jsp(117,34) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("bankList");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("                                	                     	\r\n");
            out.write("                                	<div>\r\n");
            out.write(" 									<li class=\"ms-auto\"><span class=\"counter text-success\"><li class=\"ms-auto\"><span class=\"counter text-success\"><h5 class=\"fw-bold text-dark\">account: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bankList.accountNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" \r\n");
            out.write(" 									<p>\r\n");
            out.write(" 									transfer limit: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bankList.transferLimit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" WON\r\n");
            out.write(" 									</p>\r\n");
            out.write(" 									</h5></li>                              \r\n");
            out.write("                          \r\n");
            out.write("                                	</div>   \r\n");
            out.write("                                      	\r\n");
            out.write("                           		 ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /jsp/board/dashboard.jsp(143,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("sum");
      // /jsp/board/dashboard.jsp(143,32) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/jsp/board/dashboard.jsp(143,32) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /jsp/board/dashboard.jsp(145,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/board/dashboard.jsp(145,32) '${ bankList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ bankList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /jsp/board/dashboard.jsp(145,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("bankList");
      // /jsp/board/dashboard.jsp(145,32) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("									");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("									\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /jsp/board/dashboard.jsp(147,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("sum");
      // /jsp/board/dashboard.jsp(147,9) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/jsp/board/dashboard.jsp(147,9) '${sum + bankList.balance}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sum + bankList.balance}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /jsp/board/dashboard.jsp(152,84) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sum}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /jsp/board/dashboard.jsp(251,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/board/dashboard.jsp(251,4) '${withrawalTransactionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${withrawalTransactionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /jsp/board/dashboard.jsp(251,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("withrawalTransactionList");
      // /jsp/board/dashboard.jsp(251,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<tr>\r\n");
            out.write("					 	<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['TRANNUM'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['TRANDATE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['WITHRAWALBANKNAME'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['DEPOSITBANKNAME'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['WITHRAWALACCOUNTNUM'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['DEPOSITACCOUNTNUM'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['WITHRAWALNAME']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['DEPOSITNAME'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ withrawalTransactionList['TRANAMOUNT'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>					 \r\n");
            out.write("					</tr>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /jsp/board/dashboard.jsp(300,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/board/dashboard.jsp(300,4) '${depositTransactionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${depositTransactionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /jsp/board/dashboard.jsp(300,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("depositTransactionList");
      // /jsp/board/dashboard.jsp(300,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<tr>\r\n");
            out.write("					 	<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['TRANNUM'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['TRANDATE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['WITHRAWALBANKNAME'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['DEPOSITBANKNAME'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['WITHRAWALACCOUNTNUM'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['DEPOSITACCOUNTNUM'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['WITHRAWALNAME']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['DEPOSITNAME'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td class=\"table-light\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ depositTransactionList['TRANAMOUNT'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>					 \r\n");
            out.write("					</tr>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }
}
